# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node and OSs. If a version change is detected it will also publish the package to coveralls.io and NPM.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build and test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      
      - uses: EndBug/version-check@v1
        id: check

      - name: check version changes
        if: steps.check.outputs.changed == 'true'
        run: 'echo "Version change found! New version: ${{ steps.check.outputs.version }} (${{ steps.check.outputs.type }})"'

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: npm ci
      
      - name: lint
        run: npm run lint
      
      - name: build
        run: npm run build:js
      
      - name: docs
        run: npm run docs
      
      - name: browser tests
        run: npm run test:browser-headless
      
      - name: node tests and coverage
        run: npm run coverage

      - name: send report to coveralls.io
        if: steps.check.outputs.changed == 'true' && matrix.os == 'ubuntu-latest' && matrix.node == 14
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: publish to NPM
        if: steps.check.outputs.changed == 'true' && matrix.os == 'ubuntu-latest' && matrix.node == 14
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}